import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export const generateInventoryPDF = async (data, startDate, endDate) => {
  const html = `
    <html>
      <head>
        <style>
          @page { size: A4 landscape; margin: 10mm; }
          body { font-family: 'Helvetica', sans-serif; color: #1a1a1a; padding: 20px; }
          .header { border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px; }
          .header h1 { margin: 0; font-size: 22px; text-transform: uppercase; letter-spacing: 1px; }
          .header p { margin: 5px 0; font-size: 10px; color: #666; text-transform: uppercase; }
          
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th { background: #f8f8f8; text-align: left; font-size: 9px; text-transform: uppercase; padding: 10px 5px; border-bottom: 1px solid #eee; }
          td { padding: 8px 5px; font-size: 10px; border-bottom: 0.5px solid #f0f0f0; }
          
          .brand { font-weight: 800; color: #000; }
          .price { font-family: monospace; font-weight: 600; }
          .qty-pos { color: #27ae60; font-weight: 700; }
          .qty-neg { color: #e74c3c; font-weight: 700; }
          
          .footer { margin-top: 40px; text-align: center; font-size: 9px; color: #bbb; border-top: 0.5px solid #eee; padding-top: 10px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Murlidhar Mobiles</h1>
          <p>Inventory Audit Report | Period: ${startDate} to ${endDate}</p>
        </div>

        <table>
          <thead>
            <tr>
              <th>Date/Time</th>
              <th>Brand</th>
              <th>Model / Item</th>
              <th>Type/Side</th>
              <th>Warehouse</th>
              <th>Selling</th>
              <th>Buying</th>
              <th>Trans.</th>
              <th>Stock</th>
            </tr>
          </thead>
          <tbody>
            ${data.map(item => `
              <tr>
                <td>${item.date}<br/><small>${item.time}</small></td>
                <td class="brand">${item.brand}</td>
                <td>${item.model}<br/><small style="color:#999">${item.itemGroup}</small></td>
                <td>${item.variantInfo}</td>
                <td>${item.warehouse}</td>
                <td class="price">₹${item.selling_price}</td>
                <td class="price">₹${item.buying_price}</td>
                <td class="${item.qty > 0 ? 'qty-pos' : 'qty-neg'}">${item.qty > 0 ? '+' : ''}${item.qty}</td>
                <td><b>${item.projected_qty}</b></td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        <div class="footer">
          PDF GENERATED BY STOCKMOB • ${new Date().toLocaleString()}
          Powerd By Kismattech
        </div>
      </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
};